/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Mon Dec 11 14:22:10 EST 2017
 * 
 * To automatically register this VPI wrapper with a Verilog simulator use:
 *     #include "vpi_wrapper_do_trace.h"
 *     void (*vlog_startup_routines[])() = { do_trace_vpi_register, 0u };
 * 
 * For a Verilog simulator which requires a .tab file, use the following entry:
 * $imported_do_trace call=do_trace_calltf size=1 acc=rw:%TASK
 * 
 * For a Verilog simulator which requires a .sft file, use the following entry:
 * $imported_do_trace vpiSysFuncSized 1 unsigned
 */
#include <stdlib.h>
#include <vpi_user.h>
#include "bdpi.h"

/* the type of the wrapped function */
char do_trace(char *);

/* VPI wrapper function */
PLI_INT32 do_trace_calltf(PLI_BYTE8 *user_data)
{
  vpiHandle hCall;
  char *arg_1;
  char vpi_result;
  vpiHandle *handle_array;
  
  /* retrieve handle array */
  hCall = vpi_handle(vpiSysTfCall, 0);
  handle_array = vpi_get_userdata(hCall);
  if (handle_array == NULL)
  {
    vpiHandle hArgList;
    hArgList = vpi_iterate(vpiArgument, hCall);
    handle_array = malloc(sizeof(vpiHandle) * 2u);
    handle_array[0u] = hCall;
    handle_array[1u] = vpi_scan(hArgList);
    vpi_put_userdata(hCall, handle_array);
    vpi_free_object(hArgList);
  }
  
  /* create return value */
  make_vpi_result(handle_array[0u], &vpi_result, DIRECT);
  
  /* copy in argument values */
  get_vpi_arg(handle_array[1u], &arg_1, STRING);
  
  /* call the imported C function */
  vpi_result = do_trace(arg_1);
  
  /* copy out return value */
  put_vpi_result(handle_array[0u], &vpi_result, DIRECT);
  
  /* free argument storage */
  free_vpi_args();
  vpi_free_object(hCall);
  
  return 0;
}

/* sft: $imported_do_trace vpiSysFuncSized 1 unsigned */

/* tab: $imported_do_trace call=do_trace_calltf size=1 acc=rw:%TASK */

PLI_INT32 do_trace_sizetf(PLI_BYTE8 *user_data)
{
  return 1u;
}

/* VPI wrapper registration function */
void do_trace_vpi_register()
{
  s_vpi_systf_data tf_data;
  
  /* Fill in registration data */
  tf_data.type = vpiSysFunc;
  tf_data.sysfunctype = vpiSizedFunc;
  tf_data.tfname = "$imported_do_trace";
  tf_data.calltf = do_trace_calltf;
  tf_data.compiletf = 0u;
  tf_data.sizetf = do_trace_sizetf;
  tf_data.user_data = "$imported_do_trace";
  
  /* Register the function with VPI */
  vpi_register_systf(&tf_data);
}
