/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Mon Oct 30 15:09:38 EDT 2017
 * 
 */

/* Generation options: */
#ifndef __mkTbLayerEval_h__
#define __mkTbLayerEval_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTbLayerEval module */
class MOD_mkTbLayerEval : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_cycle1;
  MOD_Reg<tUInt8> INST_le1_pe_vec_0_partialSum;
  MOD_Reg<tUInt8> INST_le1_pe_vec_0_step;
  MOD_Reg<tUInt8> INST_le1_pe_vec_0_weight_regs_0;
  MOD_Reg<tUInt8> INST_le1_pe_vec_0_weight_regs_1;
  MOD_Reg<tUInt8> INST_le1_pe_vec_0_weight_regs_2;
  MOD_Reg<tUInt8> INST_le1_pe_vec_0_weight_regs_3;
  MOD_Reg<tUInt8> INST_le1_pe_vec_0_weight_regs_4;
  MOD_Reg<tUInt8> INST_le1_pe_vec_0_weight_regs_5;
  MOD_Reg<tUInt8> INST_le1_pe_vec_0_weight_regs_6;
  MOD_Reg<tUInt8> INST_le1_pe_vec_0_weight_regs_7;
  MOD_Reg<tUInt8> INST_le1_pe_vec_1_partialSum;
  MOD_Reg<tUInt8> INST_le1_pe_vec_1_step;
  MOD_Reg<tUInt8> INST_le1_pe_vec_1_weight_regs_0;
  MOD_Reg<tUInt8> INST_le1_pe_vec_1_weight_regs_1;
  MOD_Reg<tUInt8> INST_le1_pe_vec_1_weight_regs_2;
  MOD_Reg<tUInt8> INST_le1_pe_vec_1_weight_regs_3;
  MOD_Reg<tUInt8> INST_le1_pe_vec_1_weight_regs_4;
  MOD_Reg<tUInt8> INST_le1_pe_vec_1_weight_regs_5;
  MOD_Reg<tUInt8> INST_le1_pe_vec_1_weight_regs_6;
  MOD_Reg<tUInt8> INST_le1_pe_vec_1_weight_regs_7;
  MOD_Reg<tUInt8> INST_le1_pe_vec_2_partialSum;
  MOD_Reg<tUInt8> INST_le1_pe_vec_2_step;
  MOD_Reg<tUInt8> INST_le1_pe_vec_2_weight_regs_0;
  MOD_Reg<tUInt8> INST_le1_pe_vec_2_weight_regs_1;
  MOD_Reg<tUInt8> INST_le1_pe_vec_2_weight_regs_2;
  MOD_Reg<tUInt8> INST_le1_pe_vec_2_weight_regs_3;
  MOD_Reg<tUInt8> INST_le1_pe_vec_2_weight_regs_4;
  MOD_Reg<tUInt8> INST_le1_pe_vec_2_weight_regs_5;
  MOD_Reg<tUInt8> INST_le1_pe_vec_2_weight_regs_6;
  MOD_Reg<tUInt8> INST_le1_pe_vec_2_weight_regs_7;
  MOD_Reg<tUInt8> INST_le1_pe_vec_3_partialSum;
  MOD_Reg<tUInt8> INST_le1_pe_vec_3_step;
  MOD_Reg<tUInt8> INST_le1_pe_vec_3_weight_regs_0;
  MOD_Reg<tUInt8> INST_le1_pe_vec_3_weight_regs_1;
  MOD_Reg<tUInt8> INST_le1_pe_vec_3_weight_regs_2;
  MOD_Reg<tUInt8> INST_le1_pe_vec_3_weight_regs_3;
  MOD_Reg<tUInt8> INST_le1_pe_vec_3_weight_regs_4;
  MOD_Reg<tUInt8> INST_le1_pe_vec_3_weight_regs_5;
  MOD_Reg<tUInt8> INST_le1_pe_vec_3_weight_regs_6;
  MOD_Reg<tUInt8> INST_le1_pe_vec_3_weight_regs_7;
  MOD_Reg<tUInt8> INST_le1_pe_vec_4_partialSum;
  MOD_Reg<tUInt8> INST_le1_pe_vec_4_step;
  MOD_Reg<tUInt8> INST_le1_pe_vec_4_weight_regs_0;
  MOD_Reg<tUInt8> INST_le1_pe_vec_4_weight_regs_1;
  MOD_Reg<tUInt8> INST_le1_pe_vec_4_weight_regs_2;
  MOD_Reg<tUInt8> INST_le1_pe_vec_4_weight_regs_3;
  MOD_Reg<tUInt8> INST_le1_pe_vec_4_weight_regs_4;
  MOD_Reg<tUInt8> INST_le1_pe_vec_4_weight_regs_5;
  MOD_Reg<tUInt8> INST_le1_pe_vec_4_weight_regs_6;
  MOD_Reg<tUInt8> INST_le1_pe_vec_4_weight_regs_7;
  MOD_Reg<tUInt8> INST_le1_pe_vec_5_partialSum;
  MOD_Reg<tUInt8> INST_le1_pe_vec_5_step;
  MOD_Reg<tUInt8> INST_le1_pe_vec_5_weight_regs_0;
  MOD_Reg<tUInt8> INST_le1_pe_vec_5_weight_regs_1;
  MOD_Reg<tUInt8> INST_le1_pe_vec_5_weight_regs_2;
  MOD_Reg<tUInt8> INST_le1_pe_vec_5_weight_regs_3;
  MOD_Reg<tUInt8> INST_le1_pe_vec_5_weight_regs_4;
  MOD_Reg<tUInt8> INST_le1_pe_vec_5_weight_regs_5;
  MOD_Reg<tUInt8> INST_le1_pe_vec_5_weight_regs_6;
  MOD_Reg<tUInt8> INST_le1_pe_vec_5_weight_regs_7;
  MOD_Reg<tUInt8> INST_le1_pe_vec_6_partialSum;
  MOD_Reg<tUInt8> INST_le1_pe_vec_6_step;
  MOD_Reg<tUInt8> INST_le1_pe_vec_6_weight_regs_0;
  MOD_Reg<tUInt8> INST_le1_pe_vec_6_weight_regs_1;
  MOD_Reg<tUInt8> INST_le1_pe_vec_6_weight_regs_2;
  MOD_Reg<tUInt8> INST_le1_pe_vec_6_weight_regs_3;
  MOD_Reg<tUInt8> INST_le1_pe_vec_6_weight_regs_4;
  MOD_Reg<tUInt8> INST_le1_pe_vec_6_weight_regs_5;
  MOD_Reg<tUInt8> INST_le1_pe_vec_6_weight_regs_6;
  MOD_Reg<tUInt8> INST_le1_pe_vec_6_weight_regs_7;
  MOD_Reg<tUInt8> INST_le1_pe_vec_7_partialSum;
  MOD_Reg<tUInt8> INST_le1_pe_vec_7_step;
  MOD_Reg<tUInt8> INST_le1_pe_vec_7_weight_regs_0;
  MOD_Reg<tUInt8> INST_le1_pe_vec_7_weight_regs_1;
  MOD_Reg<tUInt8> INST_le1_pe_vec_7_weight_regs_2;
  MOD_Reg<tUInt8> INST_le1_pe_vec_7_weight_regs_3;
  MOD_Reg<tUInt8> INST_le1_pe_vec_7_weight_regs_4;
  MOD_Reg<tUInt8> INST_le1_pe_vec_7_weight_regs_5;
  MOD_Reg<tUInt8> INST_le1_pe_vec_7_weight_regs_6;
  MOD_Reg<tUInt8> INST_le1_pe_vec_7_weight_regs_7;
  MOD_Reg<tUInt8> INST_le1_step;
  MOD_Reg<tUInt8> INST_pe1_partialSum;
  MOD_Reg<tUInt8> INST_pe1_step;
  MOD_Reg<tUInt8> INST_pe1_weight_regs_0;
  MOD_Reg<tUInt8> INST_pe1_weight_regs_1;
  MOD_Reg<tUInt8> INST_pe1_weight_regs_2;
  MOD_Reg<tUInt8> INST_pe1_weight_regs_3;
  MOD_Reg<tUInt8> INST_pe1_weight_regs_4;
  MOD_Reg<tUInt8> INST_pe1_weight_regs_5;
  MOD_Reg<tUInt8> INST_pe1_weight_regs_6;
  MOD_Reg<tUInt8> INST_pe1_weight_regs_7;
  MOD_Reg<tUInt8> INST_psum;
 
 /* Constructor */
 public:
  MOD_mkTbLayerEval(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt32 DEF__read__h66;
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
  void RL_test_load_weights();
  void RL_test_end();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbLayerEval &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbLayerEval &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbLayerEval &backing);
};

#endif /* ifndef __mkTbLayerEval_h__ */
